version: '3'

services:
  app:
    container_name: docker-nodejs-mongodb
    restart: always
    build: .
    ports: 
      - '4000:4000'
    links: 
      - mongo_db

  mongo_db:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    environment: 
      DB_CONNECT: mongodb+srv://admin:LcvJdrCZpPX4JN5@cluster0.znk0u.mongodb.net/?retryWrites=true&w=majority